import { resolve } from "node:path"
import { convertCircuitJsonToTscircuit } from "circuit-json-to-tscircuit"
import { parameterizeGeneratedBoard } from "../parameterize-generated-board"
import { isSourceComponent } from "./circuit-json-elements"
import { compressCircuitJson } from "./compress-circuit-json"
import { createReferenceDefinition } from "./create-reference-definition"
import { getSupportedCopperPours } from "./get-supported-copper-pours"
import {
  getRoutablePortSelectors,
  prepareConverterCircuitJson,
} from "./prepare-converter-circuit-json"
import type { ComponentName, FeatureId, ReferenceInput } from "./types"

export async function generateReferenceArtifacts(params: {
  cadModelOutputDirectory: string
  outputDirectory: string
  reference: ReferenceInput
}): Promise<void> {
  const { definition, projectCircuitJson, referenceSchematicCircuitJsons } =
    await createReferenceDefinition({
      cadModelOutputDirectory: params.cadModelOutputDirectory,
      reference: params.reference,
    })

  await Bun.write(
    resolve(params.outputDirectory, params.reference.outputName),
    createDefinitionModuleSource({
      definition,
      exportName: params.reference.exportName,
    }),
  )

  const featureIdByComponentName = new Map<ComponentName, FeatureId>(
    projectCircuitJson.filter(isSourceComponent).flatMap((element) => {
      const featureId = params.reference.getRemovableFeatureId(element.name)
      return featureId ? [[element.name, featureId] as const] : []
    }),
  )
  const generatedSource = convertCircuitJsonToTscircuit(
    prepareConverterCircuitJson(projectCircuitJson),
    { componentName: params.reference.componentName },
  )
  const parameterizedBoard = parameterizeGeneratedBoard({
    autorouterVersion: params.reference.autorouterVersion,
    componentName: params.reference.componentName,
    featureIdByComponentName,
    generatedSource,
    routablePortSelectors: getRoutablePortSelectors(projectCircuitJson),
    supportedCopperPours: getSupportedCopperPours({
      circuitJson: projectCircuitJson,
    }),
    teardropPortSelectors: new Set(
      definition.nets.flatMap((net) =>
        (net.teardropEndpoints ?? []).map(
          ({ componentName, pinKey }) => `.${componentName} > .${pinKey}`,
        ),
      ),
    ),
    viaTeardropPortSelectors: new Set(
      definition.nets.flatMap((net) =>
        net.hasViaTeardrops
          ? net.endpoints.map(({ componentName, pinKey }) => `.${componentName} > .${pinKey}`)
          : [],
      ),
    ),
  })

  await Bun.write(
    resolve(params.outputDirectory, `${params.reference.id}.circuit.tsx`),
    [
      "// Generated through Altium -> Circuit JSON -> tscircuit.",
      "// The source converter is pinned in package.json; do not edit this file by hand.",
      parameterizedBoard.source,
    ].join("\n"),
  )
  await Bun.write(
    resolve(params.outputDirectory, `${params.reference.id}.source.circuit.json.gz`),
    compressCircuitJson(projectCircuitJson),
  )
  await Promise.all(
    referenceSchematicCircuitJsons.map((schematicCircuitJson, schematicSheetIndex) =>
      Bun.write(
        resolve(
          params.outputDirectory,
          getReferenceSchematicFileName({
            referenceId: params.reference.id,
            schematicSheetIndex,
          }),
        ),
        compressCircuitJson(schematicCircuitJson),
      ),
    ),
  )

  console.log(
    `${params.reference.name}: ${parameterizedBoard.componentNames.length} generated TSX components, ${definition.nets.length} routable nets`,
  )
}

function createDefinitionModuleSource(params: { definition: object; exportName: string }): string {
  return [
    'import type { ReferenceEvmDefinition } from "../../evms/reference-evm-types"',
    "",
    "// Generated from the checksum-pinned official TI Altium release.",
    "// Run scripts/generate-ti-evm-reference-definitions.ts to regenerate.",
    `export const ${params.exportName}: ReferenceEvmDefinition = ${JSON.stringify(params.definition)}`,
    "",
  ].join("\n")
}

function getReferenceSchematicFileName(params: {
  referenceId: string
  schematicSheetIndex: number
}): string {
  return params.schematicSheetIndex === 0
    ? `${params.referenceId}.schematic.circuit.json.gz`
    : `${params.referenceId}.schematic-${params.schematicSheetIndex + 1}.circuit.json.gz`
}
